version: "3"
services:
  db:
    hostname: mysql
    image: mysql:8.4.1
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
    ports:
      - 3306:3306

volumes:
  db_data:
